### ISSUE TITLE
Compilation only works once before having to run make clean

### ISSUE THREAD

**Issue by 49616e** [retrofw/buildroot#2] opened 2020-01-20 10:46 UTC
I've been trying to use this repo to generate new rootfs images with some software that I want to use, but looks like the compilation process only works once, any attempts at recompiling the rootfs tar won't work unless I run `make clean`. This is very problematic because `make clean` deletes *all* compiled host and target toolchains, which takes several hours to compile and is (imo) completely necessary unless the config is changed. 

Edit:
My dev environment: https://app.vagrantup.com/ubuntu/boxes/xenial64
```
>>>   Sanitizing RPATH in target tree
/home/vagrant/retrofw-buildroot/support/scripts/fix-rpath target
>>>   Copying overlay overlay/root
touch /home/vagrant/retrofw-buildroot/output/target/usr
>>>   Generating root filesystem image rootfs.tar
rm -rf /home/vagrant/retrofw-buildroot/output/build/buildroot-fs
mkdir -p /home/vagrant/retrofw-buildroot/output/build/buildroot-fs
echo '#!/bin/sh' > /home/vagrant/retrofw-buildroot/output/build/buildroot-fs/fakeroot.fs
echo "set -e" >> /home/vagrant/retrofw-buildroot/output/build/buildroot-fs/fakeroot.fs
echo "chown -h -R 0:0 /home/vagrant/retrofw-buildroot/output/target" >> /home/vagrant/retrofw-buildroot/output/build/buildroot-fs/fakeroot.fs
printf '   \n' >> /home/vagrant/retrofw-buildroot/output/build/buildroot-fs/users_table.txt
PATH="/home/vagrant/retrofw-buildroot/output/host/bin:/home/vagrant/retrofw-buildroot/output/host/sbin:/home/vagrant/bin:/home/vagrant/.local/bin:/home/vagrant/bin:/home/vagrant/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" /home/vagrant/retrofw-buildroot/support/scripts/mkusers /home/vagrant/retrofw-buildroot/output/build/buildroot-fs/users_table.txt /home/vagrant/retrofw-buildroot/output/target >> /home/vagrant/retrofw-buildroot/output/build/buildroot-fs/fakeroot.fs
cat system/device_table.txt > /home/vagrant/retrofw-buildroot/output/build/buildroot-fs/device_table.txt
printf '        /bin/busybox                     f 4755 0  0 - - - - -\n /dev/console c 622 0 0 5 1 - - -\n\n' >> /home/vagrant/retrofw-buildroot/output/build/buildroot-fs/device_table.txt
echo "/home/vagrant/retrofw-buildroot/output/host/bin/makedevs -d /home/vagrant/retrofw-buildroot/output/build/buildroot-fs/device_table.txt /home/vagrant/retrofw-buildroot/output/target" >> /home/vagrant/retrofw-buildroot/output/build/buildroot-fs/fakeroot.fs
echo "echo '>>>   Executing fakeroot script overlay/retrofw.sh'" >> /home/vagrant/retrofw-buildroot/output/build/buildroot-fs/fakeroot.fs; echo PATH="/home/vagrant/retrofw-buildroot/output/host/bin:/home/vagrant/retrofw-buildroot/output/host/sbin:/home/vagrant/bin:/home/vagrant/.local/bin:/home/vagrant/bin:/home/vagrant/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" BR2_DL_DIR="/home/vagrant/retrofw-buildroot/dl" BUILD_DIR=/home/vagrant/retrofw-buildroot/output/build O=/home/vagrant/retrofw-buildroot/output overlay/retrofw.sh /home/vagrant/retrofw-buildroot/output/target "" >> /home/vagrant/retrofw-buildroot/output/build/buildroot-fs/fakeroot.fs
printf '        (cd /home/vagrant/retrofw-buildroot/output/target; find -print0 | LC_ALL=C sort -z | tar  -cf /home/vagrant/retrofw-buildroot/output/images/rootfs.tar --null --xattrs-include='\''*'\'' --no-recursion -T - --numeric-owner)\n' >> /home/vagrant/retrofw-buildroot/output/build/buildroot-fs/fakeroot.fs
chmod a+x /home/vagrant/retrofw-buildroot/output/build/buildroot-fs/fakeroot.fs
rm -f /home/vagrant/retrofw-buildroot/output/target/THIS_IS_NOT_YOUR_ROOT_FILESYSTEM
PATH="/home/vagrant/retrofw-buildroot/output/host/bin:/home/vagrant/retrofw-buildroot/output/host/sbin:/home/vagrant/bin:/home/vagrant/.local/bin:/home/vagrant/bin:/home/vagrant/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" /home/vagrant/retrofw-buildroot/output/host/bin/fakeroot -- /home/vagrant/retrofw-buildroot/output/build/buildroot-fs/fakeroot.fs
rootdir=/home/vagrant/retrofw-buildroot/output/target
table='/home/vagrant/retrofw-buildroot/output/build/buildroot-fs/device_table.txt'
makedevs: Cannot create directory `/home/vagrant/retrofw-buildroot/output/target/root': No such file or directory
makedevs: line 12: chown failed for /home/vagrant/retrofw-buildroot/output/target/root: No such file or directory
fs/tar/tar.mk:14: recipe for target '/home/vagrant/retrofw-buildroot/output/images/rootfs.tar' failed
make[1]: *** [/home/vagrant/retrofw-buildroot/output/images/rootfs.tar] Error 1
Makefile:84: recipe for target '_all' failed
make: *** [_all] Error 2
```

**Comment by glebm** [comment] 2020-01-22 21:55
Instead of running `make clean`, this works for me:

```
unlink output/target/root
```

**Comment by glebm** [comment] 2020-01-22 21:59
Looks like makedevs is trying to set permission on `/root` but RetroFW root is just a symlink that points to an absolute path that doesn't resolve there.

**Comment by pingflood** [comment] 2020-01-22 22:14
@glebm so are you facing the same issue?

I still can't reproduce in my machines. I think I'll set up a clean VM just to test this. :thinking: 

Any of you has tested with the original buildroot release? (without the RetroFW patches)
https://buildroot.org/downloads/buildroot-2018.02.11.tar.gz

**Comment by glebm** [comment] 2020-01-22 23:52
Perhaps it depends on your filesystem, does this work for you:

```
ln -s /invalid-path /tmp/abc
chmod 700 /tmp/abc || echo fail
chown root /tmp/abc || echo fail
```

**Comment by glebm** [comment] 2020-01-22 23:56
We could try a custom device table without `/root` in it:

https://github.com/retrofw/buildroot/blob/d45bc1d422ef5e3f50fe6973cd80dc075cfe1fc6/system/device_table.txt#L12

Or we could symlink `/home/retrofw` to `/root` instead of the other way around.

**Comment by 49616e** [comment] 2020-01-23 20:37
> unlink output/target/root

Works for me 😄

**Comment by pingflood** [comment] 2020-02-15 21:35
Closing because it seems to be an issue with the buildroot but not the RetroFW br itself.

**Closed by pingflood** 2020-02-15 21:35 UTC
Labels: wontfix

**Comment by glebm** [comment] 2020-02-16 12:22
Well, kind of. I think we should symlink `/home/retrofw` to `../..` instead of the other way around. Root should not be a symlink.
